# Generated by Django 3.0.1 on 2021-07-09 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerDataCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataNum', models.IntegerField(default=0, verbose_name='年份数据量')),
                ('dataBase', models.CharField(max_length=20, verbose_name='数据库名称')),
                ('year', models.IntegerField(default=0, verbose_name='年份')),
            ],
            options={
                'verbose_name': '各数据库每年数据量',
            },
        ),
    ]
